from django.conf import settings

META_PREVIEW_TWITTER_TITLE_FALLBACK = getattr(
    settings, "META_PREVIEW_TWITTER_TITLE_FALLBACK", "title",
)
META_PREVIEW_TWITTER_DESCRIPTION_FALLBACK = getattr(
    settings, "META_PREVIEW_TWITTER_DESCRIPTION_FALLBACK", "search_description",
)
META_PREVIEW_TWITTER_IMAGE_FALLBACK = getattr(
    settings, "META_PREVIEW_TWITTER_IMAGE_FALLBACK", "",
)
META_PREVIEW_TWITTER_TITLE_FIELD = getattr(
    settings, "META_PREVIEW_TWITTER_TITLE_FIELD", "twitter_title",
)
META_PREVIEW_TWITTER_DESCRIPTION_FIELD = getattr(
    settings, "META_PREVIEW_TWITTER_DESCRIPTION_FIELD", "twitter_description",
)
META_PREVIEW_TWITTER_IMAGE_FIELD = getattr(
    settings, "META_PREVIEW_TWITTER_IMAGE_FIELD", "twitter_image",
)
META_PREVIEW_TWITTER_DEFAULT_IMAGE_FUNCTION = ""
IMAGE_DEFAULT_SIZE = "fill-1200x628"
