from django.conf import settings

IMAGE_DEFAULT_SIZE = "fill-1200x628"
META_PREVIEW_TWITTER_TITLE_FALLBACK = getattr(
    settings, "META_PREVIEW_TWITTER_TITLE_FALLBACK", "title",
)
META_PREVIEW_TWITTER_DESCRIPTION_FALLBACK = getattr(
    settings, "META_PREVIEW_TWITTER_DESCRIPTION_FALLBACK", "search_description",
)
META_PREVIEW_TWITTER_IMAGE_FALLBACK = getattr(
    settings, "META_PREVIEW_TWITTER_IMAGE_FALLBACK", "",
)
META_PREVIEW_TWITTER_TITLE_FIELD = getattr(
    settings, "META_PREVIEW_TWITTER_TITLE_FIELD", "twitter_title",
)
META_PREVIEW_TWITTER_DESCRIPTION_FIELD = getattr(
    settings, "META_PREVIEW_TWITTER_DESCRIPTION_FIELD", "twitter_description",
)
META_PREVIEW_TWITTER_IMAGE_FIELD = getattr(
    settings, "META_PREVIEW_TWITTER_IMAGE_FIELD", "twitter_image",
)
META_PREVIEW_TWITTER_DEFAULT_IMAGE_FUNCTION = ""


META_PREVIEW_FACEBOOK_TITLE_FALLBACK = getattr(
    settings, "META_PREVIEW_FACEBOOK_TITLE_FALLBACK", "title",
)
META_PREVIEW_FACEBOOK_DESCRIPTION_FALLBACK = getattr(
    settings, "META_PREVIEW_FACEBOOK_DESCRIPTION_FALLBACK", "search_description",
)
META_PREVIEW_FACEBOOK_IMAGE_FALLBACK = getattr(
    settings, "META_PREVIEW_FACEBOOK_IMAGE_FALLBACK", "",
)
META_PREVIEW_FACEBOOK_TITLE_FIELD = getattr(
    settings, "META_PREVIEW_FACEBOOK_TITLE_FIELD", "og_title",
)
META_PREVIEW_FACEBOOK_DESCRIPTION_FIELD = getattr(
    settings, "META_PREVIEW_FACEBOOK_DESCRIPTION_FIELD", "og_description",
)
META_PREVIEW_FACEBOOK_IMAGE_FIELD = getattr(
    settings, "META_PREVIEW_FACEBOOK_IMAGE_FIELD", "og_image",
)
META_PREVIEW_FACEBOOK_DEFAULT_IMAGE_FUNCTION = ""
