# Generated by Django 3.0.8 on 2020-07-23 19:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail_seo_preview.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_seo_preview.mixins.FacebookSeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='SeoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_seo_preview.mixins.SeoMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='TwitterPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_seo_preview.mixins.TwitterSeoMixin, 'wagtailcore.page'),
        ),
    ]
