# Generated by Django 3.0.8 on 2020-07-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200730_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookpage',
            name='another_description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='facebookpage',
            name='another_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
