services: 
  web: 
    build: "./"
    depends_on: 
      - db
    ports: 
      - "8123:8080"
    restart: always
    volumes: 
      - "./tests:/srv/tests"
      - "./wagtail_meta_preview:/srv/wagtail_meta_preview"
      - "./settings_dev.py:/srv/settings_dev.py"
    working_dir: /srv
    environment:
      - DATABASE_HOST=db
  db:
    image: postgis/postgis:13-3.1-alpine
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
