name: Run tests, lint and publish

on: [push]

jobs:
  test:
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        wagtail-version:
          - 4.1.5
          - 5.0
          - 5.1.1
        exclude:
          - wagtail-version: 5.1.1
          - python-version: 3.7
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies & test code
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install -e .[testing]
          pip install -q wagtail==${{ matrix.wagtail-version }}
      - name: Run tests
        run: |
          python runtests.py

  lint-black:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          version: "22.3.0"

  lint-isort:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort
          isort --profile black . --check-only

  publish:
    runs-on: ubuntu-latest
    needs: [test, lint-black, lint-isort]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build
        run: |
          python -m build
      - name: Release to Test PyPi
        if: startsWith(github.ref, 'refs/tags/testv')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
        run: |
          twine upload -r testpypi dist/*
      - name: Release to PyPi
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
